import React, { useEffect } from 'react';
import ReactDOM from 'react-dom/client';
import { BrowserRouter, Routes, Route, Navigate, useNavigate } from 'react-router-dom';
import { Toaster } from 'react-hot-toast';
import { ErrorBoundary } from './components/ErrorBoundary';
import { useClaimStore } from './store/claimStore';
import { Step, DeadlineType, DeadlineStatus, DeadlinePriority, Deadline, ClaimState } from './types';
import './index.css';

// Pages
import { LandingPage } from './pages/LandingPage';
import { OnboardingPage } from './pages/OnboardingPage';
import { DashboardPage } from './pages/DashboardPage';
import { ClaimOverviewPage } from './pages/ClaimOverviewPage';
import { CalendarView } from './pages/CalendarView';
import { SettingsPage } from './pages/SettingsPage';
import { PrivacyPolicy } from './pages/PrivacyPolicy';
import { TermsOfService } from './pages/TermsOfService';
import { WizardPage } from './pages/WizardPage';
import { ConversationPage } from './pages/ConversationPage';

// Layouts
import { DashboardLayout } from './layouts/DashboardLayout';
import { WizardLayout } from './layouts/WizardLayout';

// Components
import { AddDeadlineModal } from './components/AddDeadlineModal';

// Store initializer component
const StoreInitializer: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const initialize = useClaimStore(state => state.initialize);

  useEffect(() => {
    initialize();
  }, [initialize]);

  return <>{children}</>;
};

/**
 * Determine the appropriate wizard step to resume a claim
 * Unified logic used by both CalendarPage and DashboardPage
 */
const getResumeStep = (claim: ClaimState): Step => {
  // If document was generated, go to review or draft
  if (claim.generated) {
    return claim.status === 'review' ? Step.REVIEW : Step.DRAFT;
  }
  // If document type selected, go to draft
  if (claim.selectedDocType) {
    return Step.DRAFT;
  }
  // If we have claimant/defendant data, go to verify
  if (claim.claimant?.name || claim.defendant?.name || claim.invoice?.totalAmount > 0) {
    return Step.VERIFY;
  }
  // Default to evidence step
  return Step.EVIDENCE;
};

// Calendar page wrapper that connects to store
const CalendarPage = () => {
  const navigate = useNavigate();
  const { deadlines, dashboardClaims, completeDeadline, deleteDeadline, addDeadline, setClaimData, setStep, isLoading } = useClaimStore();
  const [showAddDeadlineModal, setShowAddDeadlineModal] = React.useState(false);

  const handleSaveDeadline = async (title: string, description: string, date: string, priority: DeadlinePriority, claimId: string) => {
    const newDeadline: Deadline = {
      id: crypto.randomUUID(),
      claimId,
      type: DeadlineType.CUSTOM,
      title,
      description,
      dueDate: date,
      priority,
      status: DeadlineStatus.PENDING,
      createdAt: new Date().toISOString(),
      autoGenerated: false
    };
    await addDeadline(newDeadline);
    setShowAddDeadlineModal(false);
  };

  return (
    <>
      <CalendarView
        deadlines={deadlines}
        claims={dashboardClaims}
        isLoading={isLoading}
        onBack={() => navigate('/dashboard')}
        onDeadlineClick={(deadline) => {
          // Navigate to the claim overview for the associated deadline
          const claim = dashboardClaims.find(c => c.id === deadline.claimId);
          if (claim) {
            // Load the claim data into the store before navigating
            setClaimData(claim);
            // Navigate to claim overview page
            navigate('/claim-overview');
          }
        }}
        onCompleteDeadline={completeDeadline}
        onDeleteDeadline={deleteDeadline}
        onAddDeadline={() => setShowAddDeadlineModal(true)}
      />
      <AddDeadlineModal
        isOpen={showAddDeadlineModal}
        onClose={() => setShowAddDeadlineModal(false)}
        onSave={handleSaveDeadline}
        claims={dashboardClaims}
      />
    </>
  );
};

// New router-based app
const RouterApp = () => {
  return (
    <BrowserRouter>
      <StoreInitializer>
        {/* Toast Notifications */}
        <Toaster
          position="top-right"
          toastOptions={{
            duration: 4000,
            style: {
              background: '#fff',
              color: '#1e293b',
              border: '1px solid #e2e8f0',
              borderRadius: '0.75rem',
              boxShadow: '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
              padding: '12px 16px',
            },
            success: {
              iconTheme: {
                primary: '#0d9488',
                secondary: '#fff',
              },
            },
            error: {
              iconTheme: {
                primary: '#dc2626',
                secondary: '#fff',
              },
            },
          }}
        />
        <Routes>
          {/* Public Routes */}
          <Route path="/" element={<LandingPage />} />
          <Route path="/privacy" element={<PrivacyPolicy />} />
          <Route path="/terms" element={<TermsOfService />} />
          <Route path="/onboarding" element={<OnboardingPage />} />

          {/* Dashboard Layout Routes */}
          <Route element={<DashboardLayout />}>
            <Route path="/dashboard" element={<DashboardPage />} />
            <Route path="/claim-overview" element={<ClaimOverviewPage />} />
            <Route path="/calendar" element={<CalendarPage />} />
            <Route path="/settings" element={<SettingsPage />} />
          </Route>

          {/* Wizard Layout Routes */}
          <Route element={<WizardLayout />}>
            <Route path="/wizard" element={<WizardPage />} />
            <Route path="/conversation" element={<ConversationPage />} />
          </Route>

          {/* Fallback */}
          <Route path="*" element={<Navigate to="/" replace />} />
        </Routes>
      </StoreInitializer>
    </BrowserRouter>
  );
};

const rootElement = document.getElementById('root');
if (!rootElement) {
  throw new Error("Could not find root element to mount to");
}

const root = ReactDOM.createRoot(rootElement);
root.render(
  <React.StrictMode>
    <ErrorBoundary>
      <RouterApp />
    </ErrorBoundary>
  </React.StrictMode>
);