

export enum PartyType {
  INDIVIDUAL = 'Individual',
  BUSINESS = 'Business', // Ltd, PLC
  SOLE_TRADER = 'Sole Trader' // Self-employed individual trading as a business
}

export interface Party {
  type: PartyType;
  name: string; // Trading name or Full Name
  contactName?: string; // Contact person for correspondence
  address: string;
  city: string;
  county: string;
  postcode: string;
  phone?: string;
  email?: string;
  companyNumber?: string; // For Companies House
  solvencyStatus?: 'Active' | 'Insolvent' | 'Dissolved' | 'Unknown';
}

export interface InvoiceData {
  invoiceNumber: string;
  dateIssued: string;
  dueDate: string;
  paymentTerms?: 'net_7' | 'net_14' | 'net_30' | 'net_60' | 'net_90' | 'custom';
  agreementType?: 'goods' | 'services' | 'ongoing_contract' | 'one_time_purchase';
  totalAmount: number;
  currency: string;
  description: string;
}

export interface InterestData {
  daysOverdue: number;
  dailyRate: number;
  totalInterest: number;
}

export enum ClaimStrength {
  HIGH = 'high',
  MEDIUM = 'medium',
  LOW = 'low'
}

export interface AssessmentResult {
  isViable: boolean;
  limitationCheck: { passed: boolean; message: string }; // Limitation Act 1980
  valueCheck: { passed: boolean; message: string }; // Small claims limit
  solvencyCheck: { passed: boolean; message: string }; // Companies House status
  recommendation: string;
  // New AI Fields
  strength?: ClaimStrength; // HIGH/MEDIUM/LOW based on score
  strengthScore?: number; // 0-100 (internal use)
  strengthAnalysis?: string;
  weaknesses?: string[];
}

export enum DocumentType {
  POLITE_CHASER = 'Polite Payment Reminder',
  LBA = 'Letter Before Action',
  FORM_N1 = 'Form N1 (Claim Form)',
  DEFAULT_JUDGMENT = 'Form N225 (Default Judgment)',
  ADMISSION = 'Form N225A (Judgment - Admission)',
  DEFENCE_RESPONSE = 'Response to Defence',
  DIRECTIONS_QUESTIONNAIRE = 'Form N180 (Directions Questionnaire)',
  PART_36_OFFER = 'Part 36 Settlement Offer',
  INSTALLMENT_AGREEMENT = 'Installment Payment Agreement',
  TRIAL_BUNDLE = 'Trial Bundle',
  SKELETON_ARGUMENT = 'Skeleton Argument'
}

export interface GeneratedContent {
  documentType: DocumentType;
  content: string; // The body text
  briefDetails?: string; // For N1 Box
  legalBasis: string;
  nextSteps: string[];
  validation?: {
    isValid: boolean;
    warnings: string[];
    generatedAt: string;
  };
  review?: {
    isPass: boolean;
    critique: string;
    improvements: string[];
    correctedContent?: string; // AI Auto-fix
    wasAutoCorrected?: boolean; // True if corrections were auto-applied
    originalCritique?: string; // Preserved critique before auto-correction
    originalImprovements?: string[]; // Preserved improvements before auto-correction
  };
}

export interface TimelineEvent {
  date: string;
  description: string;
  type: 'contract' | 'service_delivered' | 'invoice' | 'payment_due' | 'part_payment' | 'chaser' | 'lba_sent' | 'acknowledgment' | 'communication' | 'payment_reminder' | 'promise_to_pay';
}

// ==========================================
// Deadline System Types
// ==========================================

export enum DeadlineType {
  LBA_RESPONSE = 'lba_response',
  COURT_FILING = 'court_filing',
  DEFENDANT_RESPONSE = 'defendant_response',
  ACKNOWLEDGMENT = 'acknowledgment',
  DEFENCE_DEADLINE = 'defence_deadline',
  JUDGMENT_DEADLINE = 'judgment_deadline',
  ENFORCEMENT = 'enforcement',
  PAYMENT_FOLLOW_UP = 'payment_follow_up',
  CUSTOM = 'custom'
}

export enum DeadlinePriority {
  CRITICAL = 'critical',
  HIGH = 'high',
  MEDIUM = 'medium',
  LOW = 'low'
}

export enum DeadlineStatus {
  PENDING = 'pending',
  COMPLETED = 'completed',
  MISSED = 'missed',
  SNOOZED = 'snoozed'
}

export interface Deadline {
  id: string;
  claimId: string;
  type: DeadlineType;
  title: string;
  description: string;
  dueDate: string; // ISO date string (YYYY-MM-DD)
  priority: DeadlinePriority;
  status: DeadlineStatus;
  createdAt: string;
  completedAt?: string;
  snoozedUntil?: string;
  autoGenerated: boolean;
  sourceEvent?: string;
  legalReference?: string;
  reminderDays?: number[];
}

export interface CalendarEvent {
  id: string;
  title: string;
  start: Date;
  end: Date;
  allDay: boolean;
  resource: {
    claimId: string;
    deadlineId?: string;
    type: 'deadline' | 'timeline_event';
    priority?: DeadlinePriority;
    status?: DeadlineStatus;
  };
}

export interface EvidenceFile {
  name: string;
  type: string; // mime type
  data: string; // base64 (raw, no prefix)
  classification?: string; // e.g., "Invoice", "Contract", "Email"
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'ai' | 'assistant';
  content: string;
  timestamp: number | string;
}

export type ClaimStatus = 'draft' | 'overdue' | 'review' | 'sent' | 'paid' | 'court' | 'judgment';

export enum ClaimStage {
  DRAFT = 'Draft',
  OVERDUE = 'Overdue',
  REMINDER_SENT = 'Reminder Sent',
  FINAL_DEMAND = 'Final Demand',
  LBA_SENT = 'LBA Sent',
  COURT_CLAIM = 'Court Claim',
  JUDGMENT = 'Judgment Obtained',
  ENFORCEMENT = 'Enforcement',
  SETTLED = 'Settled',
  ABANDONED = 'Abandoned'
}

export interface ClaimState {
  id: string;
  status: ClaimStatus;
  lastModified: number;
  source: 'manual' | 'upload' | 'xero' | 'csv';
  claimant: Party;
  defendant: Party;
  invoice: InvoiceData;
  interest: InterestData;
  compensation: number; // Late Payment of Commercial Debts Act 1998
  courtFee: number;
  timeline: TimelineEvent[];
  evidence: EvidenceFile[]; // Store multiple files
  userNotes: string;
  chatHistory: ChatMessage[];
  assessment: AssessmentResult | null;
  selectedDocType: DocumentType;
  generated: GeneratedContent | null;
  signature: string | null; // Base64 signature image
  importSource?: {
    provider: 'xero' | 'quickbooks';
    invoiceId: string;
    importedAt: string;
  };
  // LBA tracking
  lbaAlreadySent?: boolean;
  lbaSentDate?: string;
  // User document selection flag
  userSelectedDocType?: boolean;
  // Interest verification
  hasVerifiedInterest?: boolean;
  // Payment tracking
  hasPaid?: boolean;
  paymentId?: string;
  paidAt?: string;
  // Court form data for N1/N225 etc.
  courtFormData?: CourtFormData;
}

// Accounting Integration Types

export interface AccountingConnection {
  provider: 'xero' | 'quickbooks' | 'freeagent' | 'sage';
  connectionId: string; // Nango connection ID
  organizationName: string;
  connectedAt: string; // ISO timestamp
  lastSyncAt: string | null;
  tenantId?: string; // Xero tenant ID (required for Xero API calls)
}

export interface XeroInvoice {
  InvoiceID: string;
  InvoiceNumber: string;
  Type: 'ACCREC'; // Accounts Receivable
  Contact: {
    ContactID: string;
    Name: string;
  };
  Date: string; // ISO date
  DueDate: string;
  Status: 'DRAFT' | 'SUBMITTED' | 'AUTHORISED' | 'PAID' | 'VOIDED';
  LineAmountTypes: 'Exclusive' | 'Inclusive' | 'NoTax';
  SubTotal: number;
  TotalTax: number;
  Total: number;
  AmountDue: number;
  AmountPaid: number;
  CurrencyCode: string;
  Reference?: string;
}

export interface XeroContact {
  ContactID: string;
  Name: string;
  EmailAddress?: string;
  Addresses?: {
    AddressType: 'POBOX' | 'STREET';
    AddressLine1?: string;
    AddressLine2?: string;
    City?: string;
    Region?: string;
    PostalCode?: string;
    Country?: string;
  }[];
  Phones?: {
    PhoneType: 'DEFAULT' | 'MOBILE' | 'FAX';
    PhoneNumber?: string;
  }[];
}

export const INITIAL_PARTY: Party = {
  type: PartyType.BUSINESS,
  name: '',
  address: '',
  city: '',
  county: '',
  postcode: '',
  phone: '',
  email: '',
  solvencyStatus: 'Unknown'
};

export const INITIAL_INVOICE: InvoiceData = {
  invoiceNumber: '',
  dateIssued: '',
  dueDate: '',
  totalAmount: 0,
  currency: 'GBP',
  description: ''
};

export const INITIAL_INTEREST: InterestData = {
  daysOverdue: 0,
  dailyRate: 0,
  totalInterest: 0
};

export const INITIAL_STATE: ClaimState = {
  id: '',
  status: 'draft',
  lastModified: Date.now(),
  source: 'manual',
  claimant: { ...INITIAL_PARTY },
  defendant: { ...INITIAL_PARTY },
  invoice: { ...INITIAL_INVOICE },
  interest: { ...INITIAL_INTEREST },
  compensation: 0,
  courtFee: 0,
  timeline: [],
  evidence: [],
  userNotes: '',
  chatHistory: [],
  assessment: null,
  selectedDocType: DocumentType.LBA,
  generated: null,
  signature: null
};

// ==========================================
// Wizard Step Enum (5-step simplified flow)
// ==========================================
export enum Step {
  EVIDENCE = 1,
  VERIFY = 2,
  STRATEGY = 3,
  DRAFT = 4,
  REVIEW = 5
}

// ==========================================
// Conversation Types
// ==========================================
export interface ConversationMessage {
  role: 'user' | 'assistant' | 'ai';
  content: string;
  timestamp: string | number;
  attachments?: EvidenceFile[];
}

export interface ClaimIntakeResult {
  extractedData?: Partial<ClaimState>;
  followUpQuestions?: string[];
  confidence?: number;
  acknowledgment?: string;
  readyToProceed?: boolean;
  readyToExtract?: boolean;
  // Validation flags
  currencyWarning?: boolean;
  countyMissing?: boolean;
  limitationWarning?: boolean;
  debtAgeYears?: number;
  exceedsSmallClaims?: boolean;
  dateError?: boolean;
  // LBA status for document recommendation
  lbaSent?: boolean | null;
  lbaDaysAgo?: number;
}

// ==========================================
// Business & User Profile Types
// ==========================================
export enum BusinessType {
  SOLE_TRADER = 'sole_trader',
  LIMITED_COMPANY = 'limited_company',
  LLP = 'llp',
  PARTNERSHIP = 'partnership',
  OTHER = 'other'
}

export interface UserAddress {
  line1: string;
  line2?: string;
  city: string;
  county: string;
  postcode: string;
  country?: string;
}

export interface PaymentDetails {
  bankAccountHolder: string;
  bankName: string;
  sortCode: string;      // UK format: XX-XX-XX
  accountNumber: string; // 8 digits
  paymentReference?: string;
}

export const INITIAL_PAYMENT_DETAILS: PaymentDetails = {
  bankAccountHolder: '',
  bankName: '',
  sortCode: '',
  accountNumber: '',
  paymentReference: ''
};

export interface UserProfile {
  id: string;
  businessType: BusinessType;
  businessName: string;
  companyNumber?: string;
  businessAddress: UserAddress;
  email?: string;
  phone?: string;
  // Onboarding flags
  hasAuthority?: boolean;
  referralSource?: string;
  tosAcceptedAt?: string;
  disclaimerAcceptedAt?: string;
  jurisdictionConfirmed?: boolean;
  isPEP?: boolean; // Politically Exposed Person flag
  // Payment details for document generation
  paymentDetails?: PaymentDetails;
  // Metadata
  createdAt?: string;
  updatedAt?: string;
}

export const INITIAL_USER_ADDRESS: UserAddress = {
  line1: '',
  line2: '',
  city: '',
  county: '',
  postcode: '',
  country: 'United Kingdom'
};

export const INITIAL_USER_PROFILE: Omit<UserProfile, 'id'> = {
  businessType: BusinessType.SOLE_TRADER,
  businessName: '',
  companyNumber: '',
  businessAddress: { ...INITIAL_USER_ADDRESS },
  email: '',
  phone: '',
  hasAuthority: false,
  referralSource: '',
  tosAcceptedAt: undefined,
  disclaimerAcceptedAt: undefined,
  jurisdictionConfirmed: false,
  paymentDetails: { ...INITIAL_PAYMENT_DETAILS }
};

// ==========================================
// AI Extraction Types
// ==========================================
export interface ExtractedClaimData {
  claimant?: Partial<Party>;
  defendant?: Partial<Party>;
  invoice?: Partial<InvoiceData>;
  timeline?: TimelineEvent[];
  evidence?: EvidenceFile[];
  confidence?: number;
  confidenceScore?: number;
  recommendedDocument?: DocumentType;
  documentReason?: string;
  extractedFields?: string[];
}

// ==========================================
// Notification & Reminder Types
// ==========================================
export interface DeadlineReminder {
  id: string;
  deadlineId: string;
  claimId?: string;
  reminderDate: string;
  sent: boolean;
  sentAt?: string;
  emailAddress?: string;
  channel?: 'email' | 'sms' | 'push';
}

export interface UserNotificationPreferences {
  emailReminders: boolean;
  reminderDaysBefore: number[];
  digestFrequency: 'daily' | 'weekly' | 'none';
}

// ==========================================
// Court Form Types
// ==========================================
export interface CourtFormData {
  claimNumber?: string;
  admissionDate?: string;
  defendantProposal?: string;
  claimantPaymentTerms?: string;
  installmentAmount?: number;
  witnessCount?: number;
  witnessNames?: string[];
  estimatedHearingDuration?: number;
  unavailableDates?: string;
  wantsSettlementStay?: boolean;
  wantsMediation?: boolean;
  needsExpert?: boolean;
  hasDisability?: boolean;
  claimLossOfEarnings?: boolean;
}

// ==========================================
// AI Chat Types
// ==========================================
export interface ChatResponse {
  message: string;
  extractedData?: Partial<ClaimState>;
  followUpQuestions?: string[];
  readyToProceed?: boolean;
  acknowledgment?: string;
}
