import React from 'react';
import { Modal } from './ui/Modal';
import { ShieldCheck, AlertTriangle, Scale } from 'lucide-react';
import { Button } from './ui/Button';

interface LegalDisclaimerModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const LegalDisclaimerModal: React.FC<LegalDisclaimerModalProps> = ({
  isOpen,
  onClose
}) => {
  return (
    <Modal
      isOpen={isOpen}
      onClose={onClose}
      title="Legal Disclaimer"
      titleIcon={<Scale className="w-5 h-5 text-teal-600" />}
      description="Important information about using ClaimCraft UK"
      maxWidthClassName="max-w-lg"
    >
      <div className="space-y-6">
        {/* Not Legal Advice Warning */}
        <div className="bg-amber-50 border border-amber-200 rounded-lg p-4 flex gap-3">
          <AlertTriangle className="w-5 h-5 text-amber-600 flex-shrink-0 mt-0.5" />
          <div>
            <h3 className="font-semibold text-amber-900 mb-1">Not Legal Advice</h3>
            <p className="text-sm text-amber-800">
              ClaimCraft UK is a document generation and case management tool. It does not provide legal advice.
              The information and documents generated by this software should not be relied upon as legal advice.
            </p>
          </div>
        </div>

        {/* No Solicitor-Client Relationship */}
        <div>
          <h3 className="font-semibold text-slate-900 mb-2 flex items-center gap-2">
            <ShieldCheck className="w-4 h-4 text-teal-600" />
            No Solicitor-Client Relationship
          </h3>
          <p className="text-sm text-slate-700 leading-relaxed">
            Use of ClaimCraft UK does not create a solicitor-client relationship between you and the software provider.
            For specific legal advice relating to your circumstances, you should consult a qualified solicitor.
          </p>
        </div>

        {/* Pre-Action Protocol Compliance */}
        <div>
          <h3 className="font-semibold text-slate-900 mb-2 flex items-center gap-2">
            <Scale className="w-4 h-4 text-teal-600" />
            Pre-Action Protocol for Debt Claims
          </h3>
          <p className="text-sm text-slate-700 leading-relaxed mb-2">
            When pursuing debt recovery in England and Wales, you must comply with the Pre-Action Protocol for Debt Claims.
            This requires you to:
          </p>
          <ul className="text-sm text-slate-700 space-y-1 ml-4 list-disc">
            <li>Provide full details of the debt to the debtor</li>
            <li>Allow reasonable time for the debtor to respond (typically 30 days)</li>
            <li>Consider any offers of payment or disputes raised</li>
            <li>Explore alternative dispute resolution where appropriate</li>
          </ul>
        </div>

        {/* User Responsibility */}
        <div>
          <h3 className="font-semibold text-slate-900 mb-2">Your Responsibilities</h3>
          <p className="text-sm text-slate-700 leading-relaxed mb-2">
            As the user of this software, you are responsible for:
          </p>
          <ul className="text-sm text-slate-700 space-y-1 ml-4 list-disc">
            <li>Ensuring all information you enter is accurate and complete</li>
            <li>Reviewing all generated documents before sending them</li>
            <li>Complying with all applicable laws and regulations</li>
            <li>Understanding the legal processes involved in debt recovery</li>
            <li>Seeking professional legal advice when necessary</li>
          </ul>
        </div>

        {/* Data Protection */}
        <div>
          <h3 className="font-semibold text-slate-900 mb-2">Data Protection & GDPR</h3>
          <p className="text-sm text-slate-700 leading-relaxed">
            ClaimCraft UK stores all data locally in your browser. You are the data controller for any personal data
            you process using this software. Ensure you comply with UK GDPR and Data Protection Act 2018 requirements
            when handling personal information about debtors and other parties.
          </p>
        </div>

        {/* Limitation of Liability */}
        <div>
          <h3 className="font-semibold text-slate-900 mb-2">Limitation of Liability</h3>
          <p className="text-sm text-slate-700 leading-relaxed">
            The software provider accepts no liability for any losses, damages, or adverse consequences arising from
            your use of ClaimCraft UK. This includes, but is not limited to, errors in generated documents, missed
            deadlines, or unsuccessful claims.
          </p>
        </div>

        {/* When to Seek Professional Help */}
        <div className="bg-teal-50 border border-teal-200 rounded-lg p-4">
          <h3 className="font-semibold text-teal-900 mb-2">When to Seek Professional Legal Help</h3>
          <p className="text-sm text-teal-800 mb-2">
            Consider consulting a qualified solicitor if:
          </p>
          <ul className="text-sm text-teal-800 space-y-1 ml-4 list-disc">
            <li>The debt is disputed or complex</li>
            <li>You're unsure about the legal merits of your claim</li>
            <li>The debtor is insolvent or in administration</li>
            <li>You need to enforce a judgment</li>
            <li>You're facing a counterclaim or defence</li>
          </ul>
        </div>

        {/* Jurisdiction */}
        <div className="text-xs text-slate-500 pt-4 border-t border-slate-200">
          <p>
            <strong>Jurisdiction:</strong> ClaimCraft UK is designed for use in England and Wales.
            The debt recovery processes in Scotland and Northern Ireland differ significantly.
            This software should not be used for claims outside England and Wales without professional legal guidance.
          </p>
        </div>
      </div>

      {/* Footer */}
      <div className="flex justify-end pt-6 border-t border-slate-200 mt-6">
        <Button variant="primary" onClick={onClose}>
          I Understand
        </Button>
      </div>
    </Modal>
  );
};
